list: $/rv/phpconsole/models/script/columns.yaml
modelClass: RV\PhpConsole\Models\Script
title: 'rv.phpconsole::lang.controllers.scripts'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rv/phpconsole/scriptscontroller/update/:id'
